### ISSUE TITLE
Add support for named routes

### ISSUE THREAD

**Issue by MeloJR** [mrozbarry/hyperapp-router#5]
I think it would be useful to add support for named routes instead of routes by path:
```
routes: {
  home: {
    path: '/',
    OnEnter: params => state => HOME_LOGIC
  },
  profile: {
    path: '/profile',
    OnEnter: params => state => PROFILE_LOGIC
  },
}
```
another posibility would be:
```
routes: {
  '/': {
    name: 'home',
    OnEnter: params => state => HOME_LOGIC
  },
  '/profile': {
    name: 'profile',
    OnEnter: params => state => PROFILE_LOGIC
  },
}
```

It will also need that hyperapp-router export something like a `goTo` function like this:
```
goTo = (name, routeParams) => LOGIC
```
and a getUrl function to use in anchor tags:
```
getUrl = (name, routeParams) => LOGIC
```

**Comment by zaceno** [comment]
I've got to ask if there is any better example of why this is useful? To me `goTo('/profile')` is no worse as `goTo('profile')` and `href="/profile"` is even better than `href={getUrl('profile')}`

I don't see exactly what value this adds

**Comment by MeloJR** [comment]
I think that makes it easy to use for routes with complex paths, avoids typos, and enables changing the path of the route in only one place (maybe for SEO reasons o whatever).
For me is easier to do:
```
h('a', { href: getUrl('viewPost', { postId, category }) })
```
than
```
h('a', { href: `/categories/${category}/posts/{postId}` })
```
because viewPost describe the name of a route and it's improbable it will change, but paths changes and are more difficult to write well.

**Comment by mrozbarry** [comment]
I've had some more time to think about it, and I think this is a non-issue.
There's nothing wrong with making some utility file, like `urls.js` with the following:

```js
export const post => (category, id) => `/categories/${category}/posts/${id}`
```
In fact, that might be better than any solution I could bake in, because you could also easily add in some custom validation (like validating a category).

I'm going to close this for now, but I'd re-open it if there is a good reason to re-visit this.
